apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scihub-papers-pvc
  namespace: literature-downloader
spec:
  # CephFS is a shared filesystem, so the finished Job output can be
  # mounted by another Pod at the same time.
  # The consumer Pod must be in this namespace and reference this same claim.
  accessModes:
    - ReadWriteMany
  storageClassName: ceph-cephfs
  resources:
    requests:
      storage: 5Gi
